### ISSUE TITLE
Options don't set properly

### ISSUE THREAD

**Issue by distek** [atalazer/wally.nvim#1]
Hi!

First off, this is super rad. Thank you for making this!

My only issue appears to be that almost none of the options are being set before the plugin is initialized.

Here's how I have it configured currently:
```lua
require('packer').startup(function()
    use 'wbthomason/packer.nvim'
...
        use ({
            "atalazer/wally.nvim",
            run = "cp ./extra/wal/colors.lua ~/.config/wal/templates && wal -R",
            setup = function()
                vim.g.wally_wal_dir = "~/.cache/wal"
                vim.g.wally_italic_functions = true
                vim.g.wally_italic_comments = true
                vim.g.wally_italic_keywords = true
                vim.g.wally_dark_sidebar = true
                vim.g.wally_dark_float = true
                vim.g.wally_transparent = true
                vim.g.wally_transparent_sidebar = false
                vim.g.wally_sidebars = {
                    "qf",
                    "vista_kind",
                    "terminal",
                    "NvimTree",
                    "packer",
                }
            end,
            config = [[require("wally").colorscheme()]]
        })
...
```
The `wally_sidebars` section get's set correctly specifically and only for NvimTree

Am I doing something wrong here? I ended up forcing some of the options by editing config.lua manually and they seem to work this way, but this is of course not ideal.

~Also, don't know if this is related (and I don't fully understand this about packer.nvim), but wally get's placed in the `/opt` directory instead of `/start` in `~/.local/share/nvim/site/pack/packer`~
I seem to have resolved this by setting in packer just:
``` lua
        use "atalazer/wally.nvim"
```
without any of the additional options. I found this from this bit of info in the packer docs:

> 
> `use` takes either a string or a table. **If a string is provided, it is treated**
> **as a plugin location for a non-optional plugin with no additional**
> **configuration.** Plugin locations may be specified as:
>   1. Absolute paths to a local plugin
>   2. Full URLs (treated as plugins managed with `git`)
>   3. `username/repo` paths (treated as Github `git` plugins)
> 

This does require manually copying the template file to wal's config directory and running `wal -R`.

Please let me know if there's any more information you need!

**Comment by distek** [comment]
This fixed it:
```diff
diff --git a/lua/wally/config.lua b/lua/wally/config.lua
index b950bf2..fff0850 100644
--- a/lua/wally/config.lua
+++ b/lua/wally/config.lua
@@ -5,7 +5,7 @@ local config
 vim = vim or { g = {}, o = {} }
 
 local function opt(key, default)
-    key = "wally" .. key
+    key = "wally_" .. key
     if vim.g[key] == nil then
         return default
     end
```

**Comment by atalariq** [comment]
Hello! @distek 
Thanks for your review about this plugin and report this issue.
Sorry for the inconvenience, this is my bad, so I have fixed it.

**Comment by distek** [comment]
Thank you!
