### ISSUE TITLE
Lunarvim (neovim) error config

### ISSUE THREAD

**Issue by emretuna** [atalazer/wally.nvim#2]
Hi,
Thanks for the plugin. I want to use it with lunarvim (it is a pre-config based on nvim)
This is the output of the error.
`packer.nvim: Error running config for wally.nvim: ...m/site/pack/packer/start/wally.nvim/lua
/wally/colors.lua:8: module 'colors' not found:
^Ino field package.preload['colors']No cache entry
^Ino file '/home/emretuna/.cache/wal/colors.lua'
^Ino file './colors.lua'
^Ino file '/home/emretuna/Downloads/neovim/.deps/usr/share/luajit-2.1.0-beta3/colors.lua'
^Ino file '/usr/local/share/lua/5.1/colors.lua'
^Ino file '/usr/local/share/lua/5.1/colors/init.lua'
^Ino file '/home/emretuna/Downloads/neovim/.deps/usr/share/lua/5.1/colors.lua'
^Ino file '/home/emretuna/Downloads/neovim/.deps/usr/share/lua/5.1/colors/init.lua'
^Ino file '/home/emretuna/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/colors.lua'

^Ino file '/home/emretuna/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/colors/init
.lua'
^Ino file '/home/emretuna/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/co
lors.lua'
^Ino file '/home/emretuna/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/co
lors/init.lua'
^Ino file './colors.so'
^Ino file '/usr/local/lib/lua/5.1/colors.so'
^Ino file '/home/emretuna/Downloads/neovim/.deps/usr/lib/lua/5.1/colors.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'`

this is the configuration I am using 
` "atalazer/wally.nvim",
   run = "./setup.sh",
    config = function()
    require("wally").colorscheme()
    vim.cmd[[colorscheme wally]]
    vim.g.wally_wal_dir = "~/.cache/wal"
    vim.g.wally_italic_functions = true
    vim.g.wally_sidebars = { "qf", "vista_kind", "terminal", "Nvimtree", "Trouble", "packer", }
    end,
`
Do you have any idea what is causing this?

**Comment by distek** [comment]
Try adding `opt = false` to that block, like so:
```lua
"atalazer/wally.nvim",
run = "./setup.sh",
config = function()
    vim.g.wally_wal_dir = "~/.cache/wal"
    vim.g.wally_italic_functions = true
    vim.g.wally_sidebars = { "qf", "vista_kind", "terminal", "Nvimtree", "Trouble", "packer", }
    require("wally").colorscheme()
    vim.cmd[[colorscheme wally]]
end,
opt = false,
```

**Comment by emretuna** [comment]
Thanks
